esphome:
  name: transit-tracker
  friendly_name: Transit Tracker
  name_add_mac_suffix: true

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://TillFleisch/ESPHome-HUB75-MatrixDisplayWrapper@main
  - source: github://fafrd/esphome-transit-tracker@main
  - source:
      type: local
      path: ../components
    components: [transit_tracker]
    refresh: 0s

logger:
  level: INFO

wifi:
  ap:
    password: "hunter2hunter2"

captive_portal:

improv_serial:

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: ""

button:
  - platform: restart
    name: "Restart"
  - platform: template
    id: reload_tracker
    on_press:
      - lambda: |-
          id(tracker).reconnect();

text:
  - platform: template
    id: base_url_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_base_url(id(base_url_config)->state);

  - platform: template
    id: feed_code_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_feed_code(id(feed_code_config)->state);

  - platform: template
    id: schedule_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_schedule_string(id(schedule_config)->state);

  - platform: template
    id: abbreviations_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_abbreviations_from_text(id(abbreviations_config)->state);

  - platform: template
    id: route_styles_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_route_styles_from_text(id(route_styles_config)->state);

  # New text-based config to change display_mode via a POST
  - platform: template
    id: display_mode_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_display_mode_from_text(id(display_mode_config)->state);

  - platform: template
    id: limit_config
    mode: text
    optimistic: true
    restore_value: true
    on_value:
      then:
        lambda: |-
          id(tracker).set_limit(atoi(id(limit_config)->state.c_str()));

number:
  - platform: hub75_matrix_display
    matrix_id: matrix
    id: display_brightness_number

output:
  - platform: template
    id: display_brightness_output
    type: float
    write_action:
      - number.set:
          id: display_brightness_number
          value: !lambda return state * 255.0;

light:
  - platform: monochromatic
    name: Display Brightness
    id: display_brightness
    output: display_brightness_output
    restore_mode: RESTORE_DEFAULT_ON

script:
  - id: dim_display
    parameters:
      up: bool
    then:
      - light.dim_relative:
          id: display_brightness
          relative_brightness: !lambda "return up ? 0.2 : -0.2;"
          transition_length: 0.1s

binary_sensor:
  - platform: gpio
    id: up_button
    pin: &button_pin_cfg
      number: GPIO6
      inverted: true
      mode:
        input: true
        pullup: true
    filters: &button_filters
      - autorepeat:
          - delay: 500ms
            time_off: 300ms
            time_on: 100ms
    on_press:
      then:
        - script.execute:
            id: dim_display
            up: true

  - platform: gpio
    id: down_button
    pin:
      <<: *button_pin_cfg
      number: GPIO7
    filters: *button_filters
    on_press:
      then:
        - script.execute:
            id: dim_display
            up: false

display:
  - platform: hub75_matrix_display
    id: matrix
    width: 64
    height: 32
    chain_length: 2
    R1_pin: 42
    G1_pin: 40
    B1_pin: 41
    R2_pin: 38
    G2_pin: 37
    B2_pin: 39
    A_pin: 45
    B_pin: 36
    C_pin: 48
    D_pin: 35
    E_pin: 21
    LAT_pin: 47
    OE_pin: 14
    CLK_pin: 2
    clock_phase: false
    i2sspeed: HZ_20M
    brightness: 255
    lambda: |-
      id(tracker).draw_schedule();

font:
  - file: "fonts/Pixolletta8px.ttf"
    id: pixolletta
    size: 10
    glyphs:
      - abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,:;!?()"'-+/*=%@#[]{}<>|&^~
      - " "

time:
  - platform: sntp
    id: sntp_time
    timezone: America/Los_Angeles

web_server:

transit_tracker:
  id: tracker
